### ISSUE TITLE
AwaitObservable does not call cancellation continuation if the computation is canceled before the next observation

### ISSUE THREAD

**Issue by anton-pt** [fsprojects/fsharpx#316]
I posted this as a question on StackOverflow here:
http://stackoverflow.com/questions/28250201/fsharpx-async-awaitobservable-does-not-call-cancellation-continuation

It seems to me that the problem is that the definition of AwaitObservable only calls one of the continuation functions if the observable sequence has a next value (or error) before cancellation occurs. It needs to also register a callback with the cancellation token which will call the cancellation continuation and Dispose the resulting CancellationTokenRegistration on the next element in the sequence. I'm a bit out of my depth trying to implement this. Any thoughts?

**Comment by anton-pt** [comment]
I have just seen that the current version already contains this fix:
https://github.com/fsprojects/fsharpx/commit/12e93c85ac3755cdb324c9e24cb1b4b332fb1002.

I was thrown by the fact that the NuGet version doesn't have this implemented yet. Sorry about raising it.

**Comment by bennylynch** [comment]
Hello, I've got something new for you, you'll definetely love it, take a look at <http://phejyfronky.realfreedomonline.com/lnvxu>

Sincerely yours, blynch23@ntlworld.com
