### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by haf** [fsprojects/fsharpx#319]
- There hasn't been productive commits since 27th September 2014
 - There is a PR for mono support from 2012
 - Should the async seq pieces be a separate project?
 - If it's not a separate project, where are the docs on how to include only a 'single' file through paket on the home page?
 - Many PRs have been open for a year or more

**Comment by forki** [comment]
it's not exactly dead, but it still a long way to get it in good shape. 
I started by extracting parts into separate repos (see http://fsprojects.github.io/FSharpx.Collections/).

**Comment by haf** [comment]
How does one use AsyncSeq and nothing else from this lib?

**Comment by forki** [comment]
The optimal solution:
* we create a new fsprojects/FSharpx.Async project based on projectscaffold
* we copy all the async stuff over
* we make sure asyncseq.fs is independent from other files
* we release a FSharpx.Async nuget package
* optionally: we reference asyncseq.fs via paket

If you are interested then I can create the project and try to get things
started.

/cc @tpetricek

**Comment by haf** [comment]
That would be really great =). I'm redoing EventStore.Client.FSharp and I'd rather not have all the baggage this repo brings.

**Comment by DanielFabian** [comment]
One of the reasons, btw, for the long-hanging PR was the big diversity. 

Having multiple smaller projects would have two advantages:

Fewer changes needed due to size. 

Some projects would simply not be multi-platform. Thus allowing for stepwise migration. 

Dany

**Comment by forki** [comment]
https://github.com/fsprojects/FSharpx.Async is on nuget. please test and send issues there,

* reference asyncseq.fs via paket - I don' think this is possible now. There are too many other files involved.

**Comment by dsyme** [comment]
Hi @haf - AsyncSeq is now at http://fsprojects.github.io/FSharp.Control.AsyncSeq/, this will be its canonical home

**Comment by dsyme** [comment]
It does seem that the majority of functionality has now been extracted from this repo into independent components

    https://github.com/fsprojects/FSharpx.Async
    https://github.com/fsprojects/FSharpx.Collections
    https://github.com/fsprojects/FSharpx.Reflection
    https://github.com/fsprojects/FSharp.Control.AsyncSeq
    https://github.com/fsprojects/FSharp.Control.Reactive

What's left is effectively the "FSharpx.Functional" set of functionality and a few miscellaneous things (e.g. structured format)

If no one objects I'll rename this repo to "FSharpx.Functional" and delete anything that has code duplicated elsewhere.

Thanks
Don

**Comment by haf** [comment]
Thank you!

Closing!
