### ISSUE TITLE
Get(?timeout) doesn't block

### ISSUE THREAD

**Issue by haf** [fsprojects/fsharpx#36]
According to docs of Blocking Agent, it should block on get until something is available, and if nothing is then behaviour is undefined.

But docs say that it'll block.

Instead it throws TimeoutException.

I would prefer having Option<_> given, and then returning a None if the timeout expires, because afaik exceptions aren't the quickest way of handling flow control.

I'm using the project here:
https://github.com/mpsbroadband/MassTransit-AzureServiceBus/blob/integration/src/MassTransit.Async/Receiver.fs
https://github.com/mpsbroadband/MassTransit-AzureServiceBus/blob/integration/src/MassTransit.Transports.AzureServiceBus/InboundTransportImpl.cs

if you are interested in seeing it used IRL.

**Comment by dsyme** [comment]
Closing this as the relevant code has moved to http://github.com/fsprojects/FSharpx.Async.  Please reopen there if needed.
